/* STUDENTS:  DO NOT EDIT THIS FILE.  INSTEAD, CREATE YOUR OWN UNIT TESTS ACCORDING
TO THE LAB DOCUMENT.
*/

// Google Test Framework
#include <gtest/gtest.h>
// Project code from the ../src directory
#include "../src/FlyBehavior.h"
//#include <iostream>
#include <string.h>

// Initial Test for Rubber Duck.  YayYay
TEST(FlyWithRocketTest, Constructor) {
  FlyWithRocket my_rocket;
  string expect_str="Fly with wings at speed of 20 mph.";
  EXPECT_STREQ(expect_str.c_str(), my_rocket.fly().c_str())<<"FAIL: Display";
}

TEST(FlyWithRocketTest, fly) {
  FlyWithRocket my_rocket;
  string expect_str="Fly with wings at speed of 20 mph.";
  // string expect_str="Generic Flying at 5 mph.";
  EXPECT_STREQ(expect_str.c_str(), my_rocket.fly().c_str())<<"FAIL: Display";
}
