/* STUDENTS:  DO NOT EDIT THIS FILE.  INSTEAD, CREATE YOUR OWN UNIT TESTS ACCORDING
TO THE LAB DOCUMENT.
*/

// Google Test Framework
#include <gtest/gtest.h>
// Project code from the ../src directory
#include "../src/QuackBehavior.h"
//#include <iostream>
#include <string.h>

// Initial Test for Rubber Duck.  YayYay
TEST(SqueakTest, Constructor) {
  Squeak my_squeak;
  string expect_str="Quack at 10 decibels.";
  EXPECT_STREQ(expect_str.c_str(), my_squeak.quack().c_str())<<"FAIL: Display";
}

TEST(SqueakTest, quack) {
  Squeak my_squeak(2);
  string expect_str="Quack at 2 decibels.";
  EXPECT_STREQ(expect_str.c_str(), my_squeak.quack().c_str())<<"FAIL: Display";
}
